// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ValidateServiceClient is the client API for ValidateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidateServiceClient interface {
	ValidatorRPC(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type validateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidateServiceClient(cc grpc.ClientConnInterface) ValidateServiceClient {
	return &validateServiceClient{cc}
}

func (c *validateServiceClient) ValidatorRPC(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/proto.ValidateService/ValidatorRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidateServiceServer is the server API for ValidateService service.
// All implementations must embed UnimplementedValidateServiceServer
// for forward compatibility
type ValidateServiceServer interface {
	ValidatorRPC(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedValidateServiceServer()
}

// UnimplementedValidateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedValidateServiceServer struct {
}

func (UnimplementedValidateServiceServer) ValidatorRPC(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorRPC not implemented")
}
func (UnimplementedValidateServiceServer) mustEmbedUnimplementedValidateServiceServer() {}

// UnsafeValidateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidateServiceServer will
// result in compilation errors.
type UnsafeValidateServiceServer interface {
	mustEmbedUnimplementedValidateServiceServer()
}

func RegisterValidateServiceServer(s *grpc.Server, srv ValidateServiceServer) {
	s.RegisterService(&_ValidateService_serviceDesc, srv)
}

func _ValidateService_ValidatorRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateServiceServer).ValidatorRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ValidateService/ValidatorRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateServiceServer).ValidatorRPC(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ValidateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ValidateService",
	HandlerType: (*ValidateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidatorRPC",
			Handler:    _ValidateService_ValidatorRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "validator.proto",
}
